# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "vmd" "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-991ca0ab-2812-4fd1-8173-1a73c4a15083";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-991ca0ab-2812-4fd1-8173-1a73c4a15083".device = "/dev/disk/by-uuid/991ca0ab-2812-4fd1-8173-1a73c4a15083";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9243-8D92";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-43e8a04f-68af-4a55-bf28-1873d4a89773"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
